run:
  timeout: 5m
  tests: true

linters-settings:
  gocyclo:
    min-complexity: 15
  errcheck:
    check-type-assertions: true
    check-blank: true
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - govet
    - revive
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - typecheck
    - depguard
    - shadow

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - bin
    - vendor
  exclude-files:
    - ^.*_generated\.go$
  exclude-rules:
    - linters:
        - errcheck
      text: "defer .*Close.* error"

output:
  formats:
    - format: colored-line-number
