{{- if and (not .Values.tls.existingSecret) (not .Values.webhook.useCertManager) }}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "TLS Cert must be specified" .Values.tls.cert | b64enc }}
  tls.key: {{ required "TLS Key must be specified" .Values.tls.key | b64enc }}
{{- end }}