name: ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - cmd/**
      - pkg/**
      - go.mod
      - go.sum
      - docker/controller.Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Docker tag
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "docker_tag=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "docker_tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/controller.Dockerfile
          push: true
          tags: itsthatdood/namespaced-route-validator:${{ steps.vars.outputs.docker_tag }}