name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true
        cache-dependency-path: src/go.sum

    - name: Check formatting
      working-directory: src
      run: |
        fmt_out=$(go fmt ./...)
        if [ -n "$fmt_out" ]; then
          echo "The following files are not properly formatted:"
          echo "$fmt_out"
          echo "Please run 'go fmt ./...' locally."
          exit 1
        fi

    - name: Run static analysis
      working-directory: src
      run: go vet ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: run ./src --timeout=5m

    - name: Build
      working-directory: src
      run: go build -v -o ../bin/app ./...

    - name: Test
      working-directory: src
      run: go test -v ./...
