name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true
        cache-dependency-path: go.sum

    - name: Check formatting
      run: |
        fmt_out=$(go fmt ./...)
        if [ -n "$fmt_out" ]; then
          echo "The following files are not properly formatted:"
          echo "$fmt_out"
          echo "Please run 'go fmt ./...' locally."
          exit 1
        fi

    - name: Run static analysis
      run: go vet ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=5m

    - name: Build
      run: go build -v -o ../bin/controller ./cmd/controller

    - name: Test
      run: go test -v ./...

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download built binary
      uses: actions/download-artifact@v4
      with:
        name: controller
        path: bin/controller

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: bin/controller
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
